import { fakeEvm } from "@/lib/format";
import { site } from "@/lib/site";
import type { LiveToken, Market } from "@/lib/types";

export const PONS_TOKEN = "0x39dBED3a2bd333467115dE45665cC57F813C4571";
export const PONS_APP = "https://www.ponsfamily.com/launchpad";
export const PONS_DOCS = "https://docs.ponsfamily.com";
export const ORIGINATION_FEE = 0.003;
export const MIN_HEALTH = 1.05;
export const GAS_ETH = 0.00042;

function m(
  partial: Omit<Market, "address" | "originationFee"> & { address?: string }
): Market {
  return {
    originationFee: ORIGINATION_FEE,
    address: partial.address || fakeEvm(`market-${partial.id}`),
    ...partial,
  };
}

export const MARKETS: Market[] = [
  m({
    id: "eth",
    symbol: "ETH",
    name: "Ether",
    kind: "asset",
    category: "core",
    priceUsd: 2440.95,
    supplyApy: 2.84,
    borrowApy: 8.42,
    totalSupplyUsd: 8_640_000,
    totalBorrowUsd: 3_210_000,
    ltv: 0.8,
    liqThreshold: 0.85,
    liqBonus: 0.08,
    canCollateral: true,
    featured: true,
  }),
  m({
    id: "weth",
    symbol: "WETH",
    name: "Wrapped Ether",
    kind: "asset",
    category: "core",
    address: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
    priceUsd: 2440.95,
    supplyApy: 2.91,
    borrowApy: 8.18,
    totalSupplyUsd: 4_180_000,
    totalBorrowUsd: 1_640_000,
    ltv: 0.8,
    liqThreshold: 0.85,
    liqBonus: 0.08,
    canCollateral: true,
  }),
  m({
    id: "pons",
    symbol: "PONS",
    name: "pons",
    kind: "asset",
    category: "core",
    tokenId: "robinhood-pons",
    address: PONS_TOKEN,
    priceUsd: 0.0214,
    supplyApy: 14.22,
    borrowApy: 22.64,
    totalSupplyUsd: 6_420_000,
    totalBorrowUsd: 2_880_000,
    ltv: 0.7,
    liqThreshold: 0.78,
    liqBonus: 0.1,
    canCollateral: true,
    featured: true,
    ponsPair: true,
  }),
  m({
    id: "ping",
    symbol: site.tokenSymbol || "PING",
    name: site.tokenName || "Fomo Ping",
    kind: "asset",
    category: "core",
    tokenId: "robinhood-ping",
    address: site.tokenContract,
    priceUsd: 0.0144,
    supplyApy: 18.4,
    borrowApy: 28.1,
    totalSupplyUsd: 2_260_000,
    totalBorrowUsd: 940_000,
    ltv: 0.65,
    liqThreshold: 0.75,
    liqBonus: 0.12,
    canCollateral: true,
    featured: true,
    ponsPair: true,
  }),
  m({
    id: "usdg",
    symbol: "USDG",
    name: "USDG",
    kind: "asset",
    category: "stable",
    priceUsd: 1,
    supplyApy: 5.12,
    borrowApy: 9.84,
    totalSupplyUsd: 9_180_000,
    totalBorrowUsd: 4_620_000,
    ltv: 0.85,
    liqThreshold: 0.9,
    liqBonus: 0.05,
    canCollateral: true,
    featured: true,
  }),
  m({
    id: "usde",
    symbol: "USDe",
    name: "USDe",
    kind: "asset",
    category: "stable",
    tokenId: "robinhood-usde",
    priceUsd: 1,
    supplyApy: 6.44,
    borrowApy: 11.2,
    totalSupplyUsd: 3_120_000,
    totalBorrowUsd: 1_410_000,
    ltv: 0.8,
    liqThreshold: 0.86,
    liqBonus: 0.06,
    canCollateral: true,
  }),
  m({
    id: "syrupusdg",
    symbol: "syrupUSDG",
    name: "syrupUSDG",
    kind: "asset",
    category: "stable",
    tokenId: "robinhood-syrupusdg",
    priceUsd: 1.02,
    supplyApy: 7.82,
    borrowApy: 12.05,
    totalSupplyUsd: 1_630_000,
    totalBorrowUsd: 610_000,
    ltv: 0.75,
    liqThreshold: 0.82,
    liqBonus: 0.07,
    canCollateral: true,
  }),
  m({
    id: "nvda",
    symbol: "NVDA",
    name: "NVIDIA • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-nvda",
    priceUsd: 184.2,
    supplyApy: 3.41,
    borrowApy: 10.8,
    totalSupplyUsd: 1_120_000,
    totalBorrowUsd: 280_000,
    ltv: 0.55,
    liqThreshold: 0.65,
    liqBonus: 0.12,
    canCollateral: true,
  }),
  m({
    id: "aapl",
    symbol: "AAPL",
    name: "Apple • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-aapl",
    priceUsd: 228.4,
    supplyApy: 2.18,
    borrowApy: 9.2,
    totalSupplyUsd: 840_000,
    totalBorrowUsd: 190_000,
    ltv: 0.55,
    liqThreshold: 0.65,
    liqBonus: 0.12,
    canCollateral: true,
  }),
  m({
    id: "tsla",
    symbol: "TSLA",
    name: "Tesla • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-tsla",
    priceUsd: 248.1,
    supplyApy: 4.05,
    borrowApy: 13.4,
    totalSupplyUsd: 610_000,
    totalBorrowUsd: 164_000,
    ltv: 0.5,
    liqThreshold: 0.6,
    liqBonus: 0.14,
    canCollateral: true,
  }),
  m({
    id: "spy",
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-spy",
    priceUsd: 562.3,
    supplyApy: 1.88,
    borrowApy: 7.6,
    totalSupplyUsd: 1_450_000,
    totalBorrowUsd: 310_000,
    ltv: 0.6,
    liqThreshold: 0.7,
    liqBonus: 0.1,
    canCollateral: true,
  }),
  m({
    id: "meta",
    symbol: "META",
    name: "Meta Platforms • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-meta",
    priceUsd: 612.8,
    supplyApy: 2.64,
    borrowApy: 9.9,
    totalSupplyUsd: 720_000,
    totalBorrowUsd: 188_000,
    ltv: 0.55,
    liqThreshold: 0.65,
    liqBonus: 0.12,
    canCollateral: true,
  }),
  m({
    id: "googl",
    symbol: "GOOGL",
    name: "Alphabet Class A • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-googl",
    priceUsd: 174.6,
    supplyApy: 2.22,
    borrowApy: 8.7,
    totalSupplyUsd: 540_000,
    totalBorrowUsd: 121_000,
    ltv: 0.55,
    liqThreshold: 0.65,
    liqBonus: 0.12,
    canCollateral: true,
  }),
  m({
    id: "qqq",
    symbol: "QQQ",
    name: "Invesco QQQ • Robinhood Token",
    kind: "asset",
    category: "stock",
    tokenId: "robinhood-qqq",
    priceUsd: 492.5,
    supplyApy: 1.94,
    borrowApy: 7.9,
    totalSupplyUsd: 466_000,
    totalBorrowUsd: 98_000,
    ltv: 0.6,
    liqThreshold: 0.7,
    liqBonus: 0.1,
    canCollateral: true,
  }),
  m({
    id: "cashcat",
    symbol: "CASHCAT",
    name: "Cash Cat",
    kind: "asset",
    category: "meme",
    tokenId: "robinhood-cashcat",
    priceUsd: 0.084,
    supplyApy: 21.6,
    borrowApy: 36.4,
    totalSupplyUsd: 880_000,
    totalBorrowUsd: 310_000,
    ltv: 0.4,
    liqThreshold: 0.5,
    liqBonus: 0.15,
    canCollateral: true,
  }),
  m({
    id: "inu",
    symbol: "INU",
    name: "iNu",
    kind: "asset",
    category: "meme",
    tokenId: "robinhood-inu",
    priceUsd: 0.031,
    supplyApy: 24.8,
    borrowApy: 41.2,
    totalSupplyUsd: 410_000,
    totalBorrowUsd: 122_000,
    ltv: 0.35,
    liqThreshold: 0.48,
    liqBonus: 0.16,
    canCollateral: true,
  }),
  m({
    id: "hood",
    symbol: "HOOD",
    name: "TheGreenHood",
    kind: "asset",
    category: "meme",
    tokenId: "robinhood-hood",
    priceUsd: 0.112,
    supplyApy: 11.4,
    borrowApy: 19.8,
    totalSupplyUsd: 530_000,
    totalBorrowUsd: 96_000,
    ltv: 0.45,
    liqThreshold: 0.55,
    liqBonus: 0.13,
    canCollateral: true,
  }),
  m({
    id: "pons-weth",
    symbol: "PONS/WETH",
    name: "pons / WETH LP",
    kind: "lp",
    category: "lp",
    priceUsd: 86.4,
    supplyApy: 31.2,
    borrowApy: 18.6,
    totalSupplyUsd: 2_140_000,
    totalBorrowUsd: 420_000,
    ltv: 0.7,
    liqThreshold: 0.78,
    liqBonus: 0.1,
    canCollateral: true,
    featured: true,
    ponsPair: true,
  }),
  m({
    id: "pons-usdg",
    symbol: "PONS/USDG",
    name: "pons / USDG LP",
    kind: "lp",
    category: "lp",
    priceUsd: 1.42,
    supplyApy: 27.8,
    borrowApy: 16.4,
    totalSupplyUsd: 1_280_000,
    totalBorrowUsd: 260_000,
    ltv: 0.72,
    liqThreshold: 0.8,
    liqBonus: 0.09,
    canCollateral: true,
    ponsPair: true,
  }),
  m({
    id: "ping-weth",
    symbol: `${site.tokenSymbol || "PING"}/WETH`,
    name: `${site.tokenName || "Fomo Ping"} / WETH LP`,
    kind: "lp",
    category: "lp",
    priceUsd: 62.8,
    supplyApy: 34.6,
    borrowApy: 21.2,
    totalSupplyUsd: 740_000,
    totalBorrowUsd: 155_000,
    ltv: 0.62,
    liqThreshold: 0.72,
    liqBonus: 0.12,
    canCollateral: true,
    ponsPair: true,
  }),
];

export function marketById(id: string): Market | undefined {
  const lower = id.toLowerCase();
  return MARKETS.find(
    (x) =>
      x.id === id ||
      x.id === lower ||
      x.symbol.toLowerCase() === lower ||
      x.address.toLowerCase() === lower
  );
}

export function overlayMarkets(live: LiveToken | null): Market[] {
  return MARKETS.map((mkt) => {
    if (!live || !mkt.featured) return mkt;
    const isPing =
      mkt.id === "ping" ||
      mkt.symbol.toUpperCase() === (site.tokenSymbol || "PING").toUpperCase();
    if (!isPing || !(live.priceUsd > 0)) return mkt;
    return {
      ...mkt,
      symbol: live.symbol || mkt.symbol,
      name: live.name || mkt.name,
      address: live.address || mkt.address,
      priceUsd: live.priceUsd,
    };
  });
}

export function seedBag(): Record<string, number> {
  return {
    eth: 3.25,
    weth: 0.84,
    pons: 128400,
    ping: 42000,
    usdg: 18420,
    usde: 2500,
    syrupusdg: 640,
    nvda: 42,
    aapl: 38,
    tsla: 21,
    spy: 16,
    meta: 19,
    googl: 14,
    qqq: 11,
    cashcat: 8400,
    inu: 12000,
    hood: 3100,
    "pons-weth": 8.4,
    "pons-usdg": 1240,
    "ping-weth": 6.2,
  };
}

export function protocolTotals(markets: Market[]) {
  const supplied = markets.reduce((s, x) => s + x.totalSupplyUsd, 0);
  const borrowed = markets.reduce((s, x) => s + x.totalBorrowUsd, 0);
  return {
    supplied,
    borrowed,
    tvl: supplied,
    available: Math.max(0, supplied - borrowed),
  };
}
